/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_wrap = 1,
  anon_sym_var = 2,
  anon_sym_shallow = 3,
  anon_sym_LBRACK = 4,
  anon_sym_deep = 5,
  anon_sym_LT = 6,
  anon_sym_upper = 7,
  anon_sym_multi = 8,
  anon_sym_outer = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_inner = 12,
  sym_identifier = 13,
  sym_NAME = 14,
  sym_name = 15,
  sym_source_file = 16,
  sym_wrapper_decl = 17,
  sym_var_decl = 18,
  sym_shallow_decl = 19,
  sym_sa = 20,
  sym_sb = 21,
  sym_deep_decl = 22,
  sym_da = 23,
  sym_db = 24,
  sym_dc = 25,
  sym_upper_decl = 26,
  sym_multi_decl = 27,
  sym_outer_decl = 28,
  sym_inner_decl = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_outer_decl_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_wrap] = "wrap",
  [anon_sym_var] = "var",
  [anon_sym_shallow] = "shallow",
  [anon_sym_LBRACK] = "[",
  [anon_sym_deep] = "deep",
  [anon_sym_LT] = "<",
  [anon_sym_upper] = "upper",
  [anon_sym_multi] = "multi",
  [anon_sym_outer] = "outer",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_inner] = "inner",
  [sym_identifier] = "identifier",
  [sym_NAME] = "NAME",
  [sym_name] = "name",
  [sym_source_file] = "source_file",
  [sym_wrapper_decl] = "wrapper_decl",
  [sym_var_decl] = "var_decl",
  [sym_shallow_decl] = "shallow_decl",
  [sym_sa] = "sa",
  [sym_sb] = "sb",
  [sym_deep_decl] = "deep_decl",
  [sym_da] = "da",
  [sym_db] = "db",
  [sym_dc] = "dc",
  [sym_upper_decl] = "upper_decl",
  [sym_multi_decl] = "multi_decl",
  [sym_outer_decl] = "outer_decl",
  [sym_inner_decl] = "inner_decl",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_outer_decl_repeat1] = "outer_decl_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_wrap] = anon_sym_wrap,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_shallow] = anon_sym_shallow,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_deep] = anon_sym_deep,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_upper] = anon_sym_upper,
  [anon_sym_multi] = anon_sym_multi,
  [anon_sym_outer] = anon_sym_outer,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_inner] = anon_sym_inner,
  [sym_identifier] = sym_identifier,
  [sym_NAME] = sym_NAME,
  [sym_name] = sym_name,
  [sym_source_file] = sym_source_file,
  [sym_wrapper_decl] = sym_wrapper_decl,
  [sym_var_decl] = sym_var_decl,
  [sym_shallow_decl] = sym_shallow_decl,
  [sym_sa] = sym_sa,
  [sym_sb] = sym_sb,
  [sym_deep_decl] = sym_deep_decl,
  [sym_da] = sym_da,
  [sym_db] = sym_db,
  [sym_dc] = sym_dc,
  [sym_upper_decl] = sym_upper_decl,
  [sym_multi_decl] = sym_multi_decl,
  [sym_outer_decl] = sym_outer_decl,
  [sym_inner_decl] = sym_inner_decl,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_outer_decl_repeat1] = aux_sym_outer_decl_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_wrap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shallow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deep] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_upper] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_multi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_outer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inner] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_NAME] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_wrapper_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_shallow_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_sa] = {
    .visible = true,
    .named = true,
  },
  [sym_sb] = {
    .visible = true,
    .named = true,
  },
  [sym_deep_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_da] = {
    .visible = true,
    .named = true,
  },
  [sym_db] = {
    .visible = true,
    .named = true,
  },
  [sym_dc] = {
    .visible = true,
    .named = true,
  },
  [sym_upper_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_outer_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_inner_decl] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_outer_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '<', 41,
        '[', 39,
        'd', 5,
        'i', 15,
        'm', 29,
        'o', 30,
        's', 10,
        'u', 20,
        'v', 2,
        'w', 26,
        '{', 45,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(34);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(3);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 31:
      if (lookahead == 'w') ADVANCE(38);
      END_STATE();
    case 32:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 33:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 34:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_wrap);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_shallow);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_deep);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_upper);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_multi);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_outer);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_inner);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_name);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 32},
  [29] = {.lex_state = 33},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 32},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_wrap] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_shallow] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_deep] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_upper] = ACTIONS(1),
    [anon_sym_multi] = ACTIONS(1),
    [anon_sym_outer] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_inner] = ACTIONS(1),
    [sym_NAME] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym_wrapper_decl] = STATE(2),
    [sym_shallow_decl] = STATE(2),
    [sym_deep_decl] = STATE(2),
    [sym_upper_decl] = STATE(2),
    [sym_multi_decl] = STATE(2),
    [sym_outer_decl] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_wrap] = ACTIONS(5),
    [anon_sym_shallow] = ACTIONS(7),
    [anon_sym_deep] = ACTIONS(9),
    [anon_sym_upper] = ACTIONS(11),
    [anon_sym_multi] = ACTIONS(13),
    [anon_sym_outer] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_wrap,
    ACTIONS(7), 1,
      anon_sym_shallow,
    ACTIONS(9), 1,
      anon_sym_deep,
    ACTIONS(11), 1,
      anon_sym_upper,
    ACTIONS(13), 1,
      anon_sym_multi,
    ACTIONS(15), 1,
      anon_sym_outer,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(3), 7,
      sym_wrapper_decl,
      sym_shallow_decl,
      sym_deep_decl,
      sym_upper_decl,
      sym_multi_decl,
      sym_outer_decl,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_wrap,
    ACTIONS(24), 1,
      anon_sym_shallow,
    ACTIONS(27), 1,
      anon_sym_deep,
    ACTIONS(30), 1,
      anon_sym_upper,
    ACTIONS(33), 1,
      anon_sym_multi,
    ACTIONS(36), 1,
      anon_sym_outer,
    STATE(3), 7,
      sym_wrapper_decl,
      sym_shallow_decl,
      sym_deep_decl,
      sym_upper_decl,
      sym_multi_decl,
      sym_outer_decl,
      aux_sym_source_file_repeat1,
  [62] = 1,
    ACTIONS(39), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [72] = 1,
    ACTIONS(41), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [82] = 1,
    ACTIONS(43), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [92] = 1,
    ACTIONS(45), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [102] = 1,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [112] = 1,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [122] = 1,
    ACTIONS(51), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [132] = 1,
    ACTIONS(53), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [142] = 1,
    ACTIONS(55), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [152] = 1,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [162] = 1,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [172] = 1,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [182] = 1,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      anon_sym_wrap,
      anon_sym_shallow,
      anon_sym_deep,
      anon_sym_upper,
      anon_sym_multi,
      anon_sym_outer,
  [192] = 3,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(67), 1,
      anon_sym_inner,
    STATE(19), 2,
      sym_inner_decl,
      aux_sym_outer_decl_repeat1,
  [203] = 3,
    ACTIONS(67), 1,
      anon_sym_inner,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_inner_decl,
      aux_sym_outer_decl_repeat1,
  [214] = 3,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      anon_sym_inner,
    STATE(19), 2,
      sym_inner_decl,
      aux_sym_outer_decl_repeat1,
  [225] = 2,
    ACTIONS(76), 1,
      anon_sym_LT,
    STATE(14), 1,
      sym_db,
  [232] = 2,
    ACTIONS(78), 1,
      anon_sym_LBRACK,
    STATE(12), 1,
      sym_sb,
  [239] = 2,
    ACTIONS(80), 1,
      anon_sym_var,
    STATE(8), 1,
      sym_var_decl,
  [246] = 2,
    ACTIONS(82), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_sa,
  [253] = 2,
    ACTIONS(84), 1,
      anon_sym_LT,
    STATE(4), 1,
      sym_dc,
  [260] = 2,
    ACTIONS(86), 1,
      anon_sym_LT,
    STATE(6), 1,
      sym_da,
  [267] = 1,
    ACTIONS(88), 2,
      anon_sym_RBRACE,
      anon_sym_inner,
  [272] = 1,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
  [276] = 1,
    ACTIONS(92), 1,
      sym_identifier,
  [280] = 1,
    ACTIONS(94), 1,
      sym_name,
  [284] = 1,
    ACTIONS(96), 1,
      sym_identifier,
  [288] = 1,
    ACTIONS(98), 1,
      sym_NAME,
  [292] = 1,
    ACTIONS(100), 1,
      anon_sym_LBRACE,
  [296] = 1,
    ACTIONS(102), 1,
      sym_identifier,
  [300] = 1,
    ACTIONS(104), 1,
      sym_identifier,
  [304] = 1,
    ACTIONS(106), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 82,
  [SMALL_STATE(7)] = 92,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 112,
  [SMALL_STATE(10)] = 122,
  [SMALL_STATE(11)] = 132,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 152,
  [SMALL_STATE(14)] = 162,
  [SMALL_STATE(15)] = 172,
  [SMALL_STATE(16)] = 182,
  [SMALL_STATE(17)] = 192,
  [SMALL_STATE(18)] = 203,
  [SMALL_STATE(19)] = 214,
  [SMALL_STATE(20)] = 225,
  [SMALL_STATE(21)] = 232,
  [SMALL_STATE(22)] = 239,
  [SMALL_STATE(23)] = 246,
  [SMALL_STATE(24)] = 253,
  [SMALL_STATE(25)] = 260,
  [SMALL_STATE(26)] = 267,
  [SMALL_STATE(27)] = 272,
  [SMALL_STATE(28)] = 276,
  [SMALL_STATE(29)] = 280,
  [SMALL_STATE(30)] = 284,
  [SMALL_STATE(31)] = 288,
  [SMALL_STATE(32)] = 292,
  [SMALL_STATE(33)] = 296,
  [SMALL_STATE(34)] = 300,
  [SMALL_STATE(35)] = 304,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_decl, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_deep_decl, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_upper_decl, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wrapper_decl, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shallow_decl, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sb, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sa, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dc, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_da, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_outer_decl, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_outer_decl, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_outer_decl_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_outer_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inner_decl, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fake_nested(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
