--  Generated by tools/gen_unicode_tables from the Unicode Character Database
--  (UnicodeData.txt, CompositionExclusions.txt, CaseFolding.txt),
--  version 18.0.0.
--  Do not edit by hand; regenerate with `just ada-gen-unicode`.

with Synapse.Core.UTF8;

package Synapse.Core.Unicode_Tables with SPARK_Mode is

   Unicode_Version : constant String := "18.0.0";

   subtype Code_Point is UTF8.Code_Point;
   Max_Decomposition : constant := 4;
   subtype Combining_Class is Natural range 1 .. 254;

   Ccc_Count      : constant := 1002;
   Decomp_Count   : constant := 2081;
   Decomp_Data_Count : constant := 3450;
   Compose_Count  : constant := 961;
   Fold_Count     : constant := 1533;

   type Ccc_Entry is record
      CP  : Code_Point;
      Ccc : Combining_Class;
   end record;

   --  First and Length index Decomp_Item: the entry's full canonical
   --  decomposition.
   type Decomp_Entry is record
      CP     : Code_Point;
      First  : Positive;
      Length : Positive range 1 .. Max_Decomposition;
   end record;

   type Compose_Entry is record
      A, B, Composed : Code_Point;
   end record;

   type Fold_Entry is record
      CP, Folded : Code_Point;
   end record;

   --  Non-zero canonical combining classes, sorted by CP.
   function Ccc (I : Positive) return Ccc_Entry
   with Pre => I <= Ccc_Count;

   --  Full canonical decompositions, sorted by CP.
   function Decomp (I : Positive) return Decomp_Entry
   with Pre => I <= Decomp_Count;

   --  The decompositions' code points, concatenated.
   function Decomp_Item (I : Positive) return Code_Point
   with Pre => I <= Decomp_Data_Count;

   --  Primary composites, sorted by (A, B).
   function Compose (I : Positive) return Compose_Entry
   with Pre => I <= Compose_Count;

   --  Simple case folding (status C and S), sorted by CP.
   function Fold (I : Positive) return Fold_Entry
   with Pre => I <= Fold_Count;

end Synapse.Core.Unicode_Tables;
