//! Unicode NFC normalization and simple case-fold equality, built on the
//! vendored tables in `unicode_tables.zig` (regenerated by
//! `zig build gen-unicode-tables`, never edited by hand).
//!
//! Scope is deliberately narrow: canonical composition (NFC) and simple
//! case folding for equality comparison, nothing else. No full Unicode
//! case mapping (locale-sensitive exceptions like Turkish dotless i are
//! unneeded for comparison), no diacritic/script-variant equivalence
//! (Arabic/Hebrew with vs. without vowel points, Kanji vs. Hiragana) --
//! those are linguistic stemming problems, not encoding ones.

const std = @import("std");
const tables = @import("unicode_tables.zig");

const Allocator = std.mem.Allocator;

// Hangul syllable algorithmic decomposition/composition (UAX #15) --
// Hangul jamo carry no decomposition mapping in the UCD and combining
// class 0, so they're handled here rather than through the vendored
// tables at all.
const hangul_sbase: u21 = 0xAC00;
const hangul_lbase: u21 = 0x1100;
const hangul_vbase: u21 = 0x1161;
const hangul_tbase: u21 = 0x11A7;
const hangul_lcount: u21 = 19;
const hangul_vcount: u21 = 21;
const hangul_tcount: u21 = 28;
const hangul_ncount: u21 = hangul_vcount * hangul_tcount;
const hangul_scount: u21 = hangul_lcount * hangul_ncount;

fn isHangulSyllable(cp: u21) bool {
    return cp >= hangul_sbase and cp < hangul_sbase + hangul_scount;
}

/// Canonical combining class -- 0 (a starter) for anything not in the
/// vendored table, which lists only nonzero entries.
fn combiningClass(cp: u21) u8 {
    var lo: usize = 0;
    var hi: usize = tables.ccc_table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = tables.ccc_table[mid];
        if (e.cp == cp) return e.ccc;
        if (e.cp < cp) lo = mid + 1 else hi = mid;
    }
    return 0;
}

fn tableDecomposition(cp: u21) ?[]const u21 {
    var lo: usize = 0;
    var hi: usize = tables.decomp_table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = tables.decomp_table[mid];
        if (e.cp == cp) return e.seq;
        if (e.cp < cp) lo = mid + 1 else hi = mid;
    }
    return null;
}

/// Full canonical decomposition, recursive, Hangul handled algorithmically.
fn decomposeInto(out: *std.ArrayListUnmanaged(u21), gpa: Allocator, cp: u21) !void {
    if (isHangulSyllable(cp)) {
        const s_index = cp - hangul_sbase;
        const l = hangul_lbase + s_index / hangul_ncount;
        const v = hangul_vbase + (s_index % hangul_ncount) / hangul_tcount;
        const t_index = s_index % hangul_tcount;
        try out.append(gpa, l);
        try out.append(gpa, v);
        if (t_index != 0) try out.append(gpa, hangul_tbase + t_index);
        return;
    }
    if (tableDecomposition(cp)) |seq| {
        for (seq) |c| try decomposeInto(out, gpa, c);
        return;
    }
    try out.append(gpa, cp);
}

/// In-place stable reordering by combining class within each maximal run
/// of non-starters -- a starter (class 0) is a hard boundary nothing
/// crosses.
fn canonicalOrder(seq: []u21) void {
    var i: usize = 1;
    while (i < seq.len) : (i += 1) {
        if (combiningClass(seq[i]) == 0) continue;
        var j = i;
        while (j > 0 and combiningClass(seq[j - 1]) != 0 and
            combiningClass(seq[j - 1]) > combiningClass(seq[j]))
        {
            std.mem.swap(u21, &seq[j - 1], &seq[j]);
            j -= 1;
        }
    }
}

fn tableCompose(a: u21, b: u21) ?u21 {
    var lo: usize = 0;
    var hi: usize = tables.compose_table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = tables.compose_table[mid];
        if (e.a == a and e.b == b) return e.composed;
        const less = if (e.a != a) e.a < a else e.b < b;
        if (less) lo = mid + 1 else hi = mid;
    }
    return null;
}

fn composePair(a: u21, b: u21) ?u21 {
    // Hangul L + V -> LV syllable (no trailing consonant).
    if (a >= hangul_lbase and a < hangul_lbase + hangul_lcount and
        b >= hangul_vbase and b < hangul_vbase + hangul_vcount)
    {
        const l_index = a - hangul_lbase;
        const v_index = b - hangul_vbase;
        return hangul_sbase + (l_index * hangul_vcount + v_index) * hangul_tcount;
    }
    // Hangul LV + T -> LVT syllable, only when `a` has no trailing
    // consonant yet and `b` is a real trailing consonant (not "none").
    if (isHangulSyllable(a) and (a - hangul_sbase) % hangul_tcount == 0 and
        b > hangul_tbase and b < hangul_tbase + hangul_tcount)
    {
        return a + (b - hangul_tbase);
    }
    return tableCompose(a, b);
}

/// Canonical composition over an already fully-decomposed,
/// canonically-ordered sequence -- the "compose" half of NFC.
fn compose(seq: []const u21, out: *std.ArrayListUnmanaged(u21), gpa: Allocator) !void {
    if (seq.len == 0) return;
    try out.append(gpa, seq[0]);
    var starter_index: usize = 0;
    var last_class: u8 = combiningClass(seq[0]);
    for (seq[1..]) |c| {
        const cc = combiningClass(c);
        if ((last_class == 0 or last_class < cc) and composePair(out.items[starter_index], c) != null) {
            out.items[starter_index] = composePair(out.items[starter_index], c).?;
            continue;
        }
        try out.append(gpa, c);
        if (cc == 0) starter_index = out.items.len - 1;
        last_class = cc;
    }
}

/// NFC-normalizes `s`. Caller owns the result.
pub fn normalizeNfc(gpa: Allocator, s: []const u8) ![]u8 {
    const view = std.unicode.Utf8View.init(s) catch return gpa.dupe(u8, s);

    var decomposed: std.ArrayListUnmanaged(u21) = .empty;
    defer decomposed.deinit(gpa);
    var it = view.iterator();
    while (it.nextCodepoint()) |cp| try decomposeInto(&decomposed, gpa, cp);

    canonicalOrder(decomposed.items);

    var composed: std.ArrayListUnmanaged(u21) = .empty;
    defer composed.deinit(gpa);
    try compose(decomposed.items, &composed, gpa);

    var out: std.ArrayListUnmanaged(u8) = .empty;
    errdefer out.deinit(gpa);
    var buf: [4]u8 = undefined;
    for (composed.items) |cp| {
        const n = std.unicode.utf8Encode(cp, &buf) catch continue;
        try out.appendSlice(gpa, buf[0..n]);
    }
    return out.toOwnedSlice(gpa);
}

fn simpleFold(cp: u21) u21 {
    var lo: usize = 0;
    var hi: usize = tables.casefold_table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = tables.casefold_table[mid];
        if (e.cp == cp) return e.folded;
        if (e.cp < cp) lo = mid + 1 else hi = mid;
    }
    return cp;
}

/// Case-fold equality over the raw UTF-8 bytes -- no normalization first,
/// so a precomposed vs. decomposed spelling of the same text still needs
/// `normalizeNfc` on both sides before this if that distinction matters
/// too. Invalid UTF-8 on either side compares unequal rather than panicking.
pub fn eqlCaseFold(a: []const u8, b: []const u8) bool {
    const av = std.unicode.Utf8View.init(a) catch return false;
    const bv = std.unicode.Utf8View.init(b) catch return false;
    var ai = av.iterator();
    var bi = bv.iterator();
    while (true) {
        const ac = ai.nextCodepoint();
        const bc = bi.nextCodepoint();
        if (ac == null or bc == null) return ac == null and bc == null;
        if (simpleFold(ac.?) != simpleFold(bc.?)) return false;
    }
}

/// `s`, case-folded, as newly allocated bytes -- for building a case-fold
/// hashmap key (`std.ascii.allocLowerString`'s role, generalized past
/// ASCII). Caller frees. Invalid UTF-8 passes through unfolded rather than
/// erroring, matching `eqlCaseFold`'s fail-safe-unequal spirit: a key built
/// from raw bytes still works as a key, just without folding.
pub fn foldAlloc(gpa: Allocator, s: []const u8) ![]u8 {
    const view = std.unicode.Utf8View.init(s) catch return gpa.dupe(u8, s);
    var out: std.ArrayListUnmanaged(u8) = .empty;
    errdefer out.deinit(gpa);
    var it = view.iterator();
    var buf: [4]u8 = undefined;
    while (it.nextCodepoint()) |cp| {
        const n = std.unicode.utf8Encode(simpleFold(cp), &buf) catch continue;
        try out.appendSlice(gpa, buf[0..n]);
    }
    return out.toOwnedSlice(gpa);
}

/// `s`, NFC-normalized then case-folded, as newly allocated bytes -- a
/// canonical comparison key for a hashmap keyed on note title, so two
/// spellings of the same title (different case, or different NFC
/// composition) always land on the same key. Caller frees.
pub fn normalizeKeyAlloc(gpa: Allocator, s: []const u8) ![]u8 {
    const nfc = try normalizeNfc(gpa, s);
    defer gpa.free(nfc);
    return foldAlloc(gpa, nfc);
}

pub const CaseFoldMatch = struct { start: usize, end: usize };

/// The first case-fold match of `needle` in `haystack`, as a byte range --
/// `end - start` is the matched span's own byte length, which can differ
/// from `needle.len` (folding is 1 codepoint in, 1 codepoint out, but a
/// codepoint's UTF-8 encoding length can still differ between the two
/// sides). No allocation: re-decodes `needle` once per candidate start
/// position, fine for the short, note-sized text every caller here scans.
pub fn findCaseFold(haystack: []const u8, needle: []const u8) ?CaseFoldMatch {
    if (needle.len == 0) return null;
    const hview = std.unicode.Utf8View.init(haystack) catch return null;
    const nview = std.unicode.Utf8View.init(needle) catch return null;

    var outer = hview.iterator();
    while (true) {
        const start = outer.i;
        var h = outer;
        var n = nview.iterator();
        var matched = true;
        while (n.nextCodepoint()) |ncp| {
            const hcp = h.nextCodepoint() orelse {
                matched = false;
                break;
            };
            if (simpleFold(hcp) != simpleFold(ncp)) {
                matched = false;
                break;
            }
        }
        if (matched) return .{ .start = start, .end = h.i };
        if (outer.nextCodepoint() == null) return null;
    }
}

/// Whether `haystack` contains `needle` at all, case-fold-aware -- the
/// `std.ascii.findIgnoreCase(...) != null` shape, generalized past ASCII.
pub fn containsCaseFold(haystack: []const u8, needle: []const u8) bool {
    return findCaseFold(haystack, needle) != null;
}

/// Non-overlapping case-fold occurrence count -- `countIgnoreCase`'s role,
/// generalized past ASCII. An empty needle counts zero, same as before.
pub fn countCaseFold(haystack: []const u8, needle: []const u8) usize {
    if (needle.len == 0) return 0;
    var count: usize = 0;
    var pos: usize = 0;
    while (pos <= haystack.len) {
        const m = findCaseFold(haystack[pos..], needle) orelse break;
        count += 1;
        pos += m.end;
    }
    return count;
}

const testing = std.testing;

test "normalizeNfc composes a decomposed accent onto its base letter" {
    const gpa = testing.allocator;
    // "e" + combining acute (U+0301) -> precomposed "é" (U+00E9).
    const decomposed = "e\u{0301}";
    const got = try normalizeNfc(gpa, decomposed);
    defer gpa.free(got);
    try testing.expectEqualStrings("\u{00E9}", got);
}

test "normalizeNfc is a no-op on text already in precomposed form" {
    const gpa = testing.allocator;
    const got = try normalizeNfc(gpa, "café");
    defer gpa.free(got);
    try testing.expectEqualStrings("café", got);
}

test "normalizeNfc composes a Japanese dakuten mark onto its kana" {
    const gpa = testing.allocator;
    // か (U+304B) + combining dakuten (U+3099) -> が (U+304C).
    const decomposed = "\u{304B}\u{3099}";
    const got = try normalizeNfc(gpa, decomposed);
    defer gpa.free(got);
    try testing.expectEqualStrings("\u{304C}", got);
}

test "normalizeNfc composes decomposed Hangul jamo into a syllable" {
    const gpa = testing.allocator;
    // L (U+1100) + V (U+1161) -> 가 (U+AC00).
    const decomposed = "\u{1100}\u{1161}";
    const got = try normalizeNfc(gpa, decomposed);
    defer gpa.free(got);
    try testing.expectEqualStrings("\u{AC00}", got);
}

test "eqlCaseFold matches Cyrillic regardless of case" {
    try testing.expect(eqlCaseFold("МОСКВА", "Москва"));
    try testing.expect(!eqlCaseFold("Москва", "Киев"));
}

test "eqlCaseFold matches ASCII regardless of case, same as before" {
    try testing.expect(eqlCaseFold("Foo", "foo"));
    try testing.expect(!eqlCaseFold("Foo", "Bar"));
}

test "eqlCaseFold is false on invalid UTF-8 rather than panicking" {
    try testing.expect(!eqlCaseFold("\xff\xfe", "ok"));
}

test "foldAlloc lowercases Cyrillic the same way ASCII lowercasing already works" {
    const gpa = testing.allocator;
    const got = try foldAlloc(gpa, "МОСКВА");
    defer gpa.free(got);
    try testing.expectEqualStrings("москва", got);
}

test "findCaseFold finds a Cyrillic needle regardless of case" {
    const m = findCaseFold("город МОСКВА река", "Москва").?;
    try testing.expectEqualStrings("МОСКВА", "город МОСКВА река"[m.start..m.end]);
}

test "findCaseFold returns null when nothing matches" {
    try testing.expectEqual(@as(?CaseFoldMatch, null), findCaseFold("город Киев", "Москва"));
}

test "countCaseFold counts every occurrence regardless of case, non-Latin included" {
    try testing.expectEqual(@as(usize, 3), countCaseFold("Москва москва МОСКВА Киев", "москва"));
}

test "countCaseFold with an empty needle is zero, not every position" {
    try testing.expectEqual(@as(usize, 0), countCaseFold("anything", ""));
}
