//! Grammar preparation: from a registry entry to a loaded `TSLanguage`.
//!
//! Replaces what `synapse-tags.sh` delegated to the tree-sitter CLI and to
//! `git`. The steps are the same ones the script performed -- clone the
//! grammar repo on first use, under a lock, into the grammars directory --
//! plus the one the CLI used to do invisibly: compile the parser. Doing it
//! ourselves is what removes the CLI, and with it Node.
//!
//! A C compiler is still required at runtime, and that is not a regression to
//! apologise for so much as a fact to state: a grammar cloned at runtime has
//! to be compiled by something, and this binary is not a compiler. `zig cc` is
//! preferred where Zig is installed, since it is the same toolchain the binary
//! was built with; plain `cc` is the fallback, which is exactly what the shell
//! script required too.

const std = @import("std");
const root = @import("root.zig");
const process = @import("adapters").process;

const c = root.c;
const Io = std.Io;
const Allocator = std.mem.Allocator;

pub const Error = error{
    NoCompiler,
    CloneFailed,
    CompileFailed,
    ParserSourceMissing,
    SymbolNotFound,
    /// The grammar was generated by a newer tree-sitter than the pinned
    /// libtree-sitter understands. Reported rather than crashed on, because
    /// `ts_parser_set_language` would otherwise just refuse with no reason.
    AbiUnsupported,
};

/// `tree-sitter-java` -> `tree_sitter_java`. Derived from the repo name, the
/// way the CLI derives it, which is right for every grammar whose repo holds
/// exactly one language. A repo shipping two (tree-sitter-typescript, with
/// `typescript` and `tsx`) will need the registry entry to name the symbol
/// explicitly; nothing here guesses a second one.
pub fn symbolFor(gpa: Allocator, repo_name: []const u8) ![]u8 {
    const stem = if (std.mem.startsWith(u8, repo_name, "tree-sitter-"))
        repo_name["tree-sitter-".len..]
    else
        repo_name;
    const out = try gpa.alloc(u8, "tree_sitter_".len + stem.len);
    @memcpy(out[0.."tree_sitter_".len], "tree_sitter_");
    for (stem, 0..) |ch, i| out["tree_sitter_".len + i] = if (ch == '-') '_' else ch;
    return out;
}

/// The platform's shared-library extension. Grammars are loaded with
/// `std.DynLib`, which is `dlopen` on POSIX and `LoadLibrary` on Windows, so
/// the only per-platform detail is the file name.
pub fn sharedLibExt() []const u8 {
    return switch (@import("builtin").os.tag) {
        .windows => "dll",
        .macos, .ios, .watchos, .tvos => "dylib",
        else => "so",
    };
}

/// `basename` of a git URL with any `.git` suffix removed, matching the
/// script's `basename "$repo" .git`.
pub fn repoNameOf(url: []const u8) []const u8 {
    const trimmed = std.mem.trimEnd(u8, url, "/");
    const base = std.fs.path.basename(trimmed);
    return if (std.mem.endsWith(u8, base, ".git")) base[0 .. base.len - ".git".len] else base;
}

/// Which compiler to build grammars with. `zig cc` first: it is the same
/// toolchain this binary was built with, it cross-compiles, and on a machine
/// that installed synapse from source it is already present.
pub fn findCompiler(io: Io, gpa: Allocator) !struct { argv0: []const u8, sub: ?[]const u8 } {
    if (probe(io, gpa, &.{ "zig", "version" })) return .{ .argv0 = "zig", .sub = "cc" };
    if (probe(io, gpa, &.{ "cc", "--version" })) return .{ .argv0 = "cc", .sub = null };
    return Error.NoCompiler;
}

fn probe(io: Io, gpa: Allocator, argv: []const []const u8) bool {
    const res = process.run(io, gpa, argv, .{}) catch return false;
    defer res.deinit(gpa);
    return res.ok();
}

/// Build `repo_dir/src/parser.c` (plus `scanner.c` when present) into
/// `out_path`. Returns silently if `out_path` is already newer than the
/// sources -- a grammar is compiled once and reused, exactly as the CLI's own
/// build cache behaved.
pub fn build(io: Io, gpa: Allocator, repo_dir: []const u8, out_path: []const u8) !void {
    const cwd = Io.Dir.cwd();

    const parser_c = try std.fs.path.join(gpa, &.{ repo_dir, "src", "parser.c" });
    defer gpa.free(parser_c);
    cwd.access(io, parser_c, .{}) catch return Error.ParserSourceMissing;

    if (try upToDate(io, out_path, parser_c)) return;

    const src_dir = try std.fs.path.join(gpa, &.{ repo_dir, "src" });
    defer gpa.free(src_dir);
    const include = try std.fmt.allocPrint(gpa, "-I{s}", .{src_dir});
    defer gpa.free(include);

    const compiler = try findCompiler(io, gpa);

    var argv: std.ArrayListUnmanaged([]const u8) = .empty;
    defer argv.deinit(gpa);
    try argv.append(gpa, compiler.argv0);
    if (compiler.sub) |s| try argv.append(gpa, s);
    // -fPIC and -shared are what make it loadable; -O2 because a parser is
    // hot and this is paid once. No -march=native: the artefact is cached on
    // disk and may outlive the machine that built it.
    try argv.appendSlice(gpa, &.{ "-shared", "-fPIC", "-O2", include, "-o", out_path, parser_c });

    // Some grammars carry an external scanner. C is common (python, kotlin);
    // C++ (`scanner.cc`) exists too and would need `zig c++` plus libc++, so
    // it is refused loudly rather than compiled into a link error.
    const scanner_c = try std.fs.path.join(gpa, &.{ repo_dir, "src", "scanner.c" });
    defer gpa.free(scanner_c);
    const scanner_cc = try std.fs.path.join(gpa, &.{ repo_dir, "src", "scanner.cc" });
    defer gpa.free(scanner_cc);
    if (cwd.access(io, scanner_c, .{})) |_| {
        try argv.append(gpa, scanner_c);
    } else |_| if (cwd.access(io, scanner_cc, .{})) |_| {
        std.debug.print(
            "synapse: {s} has a C++ scanner, which is not supported yet -- skipping that grammar\n",
            .{repo_dir},
        );
        return Error.CompileFailed;
    } else |_| {}

    if (std.fs.path.dirname(out_path)) |dir| cwd.createDirPath(io, dir) catch {};

    const res = try process.run(io, gpa, argv.items, .{});
    defer res.deinit(gpa);
    if (!res.ok()) {
        std.debug.print("synapse: compiling {s} failed:\n{s}\n", .{ repo_dir, res.stderr });
        return Error.CompileFailed;
    }
}

fn upToDate(io: Io, out_path: []const u8, source: []const u8) !bool {
    const cwd = Io.Dir.cwd();
    const out = cwd.statFile(io, out_path, .{}) catch return false;
    const src = cwd.statFile(io, source, .{}) catch return false;
    return out.mtime.nanoseconds >= src.mtime.nanoseconds;
}

/// Clone a grammar repo on first use, into `repos_parent/<name>`, and return
/// that directory. Already present means nothing to do.
///
/// The lock is not belt-and-braces. Callers tag in parallel chunks, and each
/// worker runs this same readiness check independently: without it, two
/// workers seeing the same missing directory both start a clone, git refuses
/// the second because the destination is not empty, and that worker's failure
/// path removes the directory out from under the first one's still-running
/// clone. `createDir` is atomic across processes on a POSIX filesystem, so
/// exactly one worker wins and the rest wait for it rather than racing a
/// second clone in.
pub fn ensureCloned(
    io: Io,
    gpa: Allocator,
    repo_url: []const u8,
    repos_parent: []const u8,
    max_tries: usize,
) ![]u8 {
    const cwd = Io.Dir.cwd();
    const repo_dir = try std.fs.path.join(gpa, &.{ repos_parent, repoNameOf(repo_url) });
    errdefer gpa.free(repo_dir);

    if (cwd.access(io, repo_dir, .{})) |_| return repo_dir else |_| {}

    try cwd.createDirPath(io, repos_parent);

    const lock_dir = try std.fmt.allocPrint(gpa, "{s}.lock", .{repo_dir});
    defer gpa.free(lock_dir);

    var got_lock = false;
    var tries: usize = 0;
    while (tries < max_tries) : (tries += 1) {
        if (cwd.createDir(io, lock_dir, .default_dir)) |_| {
            got_lock = true;
            break;
        } else |_| {}
        // The holder may have finished and released between our check above
        // and this attempt, in which case there is nothing left to wait for.
        if (cwd.access(io, repo_dir, .{})) |_| break else |_| {}
        std.Io.sleep(io, .fromMilliseconds(200), .awake) catch {};
    }

    if (got_lock) {
        defer cwd.deleteDir(io, lock_dir) catch {};
        // Re-check under the lock: a worker may have cloned, finished and
        // released between our last look and our acquiring it.
        if (cwd.access(io, repo_dir, .{})) |_| return repo_dir else |_| {}

        const res = try process.run(io, gpa, &.{ "git", "clone", "--depth", "1", "-q", repo_url, repo_dir }, .{});
        defer res.deinit(gpa);
        if (!res.ok()) {
            cwd.deleteTree(io, repo_dir) catch {};
            return Error.CloneFailed;
        }
        return repo_dir;
    }

    // Never got the lock and the directory still is not there: the holder
    // either died or is slower than the ceiling allows. Failing is right --
    // racing a second clone into a half-cloned directory is how the first
    // one gets destroyed.
    cwd.access(io, repo_dir, .{}) catch return Error.CloneFailed;
    return repo_dir;
}

/// Load a built grammar and hand back its language, refusing an ABI the pinned
/// libtree-sitter cannot parse with rather than letting the failure surface
/// later as an unexplained parse of nothing.
pub fn load(gpa: Allocator, lib_path: []const u8, symbol: []const u8) !*const c.TSLanguage {
    var lib = try std.DynLib.open(lib_path);
    // Deliberately not closed: the returned TSLanguage points into this image,
    // and every caller keeps using it for the life of the process. Closing
    // here is a use-after-free that only shows up under load.
    const sym = try gpa.dupeZ(u8, symbol);
    defer gpa.free(sym);

    const LangFn = *const fn () callconv(.c) ?*const c.TSLanguage;
    const fn_ptr = lib.lookup(LangFn, sym) orelse return Error.SymbolNotFound;
    const lang = fn_ptr() orelse return Error.SymbolNotFound;

    const abi = c.ts_language_abi_version(lang);
    if (abi < root.abi_min or abi > root.abi_max) return Error.AbiUnsupported;
    return lang;
}

const testing = std.testing;

test "symbol names are derived the way the CLI derives them" {
    const gpa = testing.allocator;
    const java = try symbolFor(gpa, "tree-sitter-java");
    defer gpa.free(java);
    try testing.expectEqualStrings("tree_sitter_java", java);

    // Hyphens inside the language name become underscores, or dlsym misses.
    const embedded = try symbolFor(gpa, "tree-sitter-embedded-template");
    defer gpa.free(embedded);
    try testing.expectEqualStrings("tree_sitter_embedded_template", embedded);
}

test "repo names come off a URL with or without .git" {
    try testing.expectEqualStrings("tree-sitter-java", repoNameOf("https://github.com/tree-sitter/tree-sitter-java"));
    try testing.expectEqualStrings("tree-sitter-java", repoNameOf("https://github.com/tree-sitter/tree-sitter-java.git"));
    try testing.expectEqualStrings("tree-sitter-java", repoNameOf("git@github.com:tree-sitter/tree-sitter-java.git"));
}

test "a compiler is found on this machine" {
    var t: std.Io.Threaded = .init(testing.allocator, .{});
    defer t.deinit();
    const found = try findCompiler(t.io(), testing.allocator);
    try testing.expect(found.argv0.len > 0);
}

test "end to end: compile a source tree and load a symbol out of it" {
    // A stand-in grammar rather than a real one: it exercises compiler
    // discovery, argv construction, the spawn, the up-to-date short-circuit,
    // DynLib open and symbol lookup, without needing the network or whatever
    // happens to be in the developer's grammar cache. The real grammars are
    // covered by the differential against the tree-sitter CLI.
    const gpa = testing.allocator;
    var t: std.Io.Threaded = .init(gpa, .{});
    defer t.deinit();
    const io = t.io();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const dir = buf[0..try tmp.dir.realPath(io, &buf)];

    try tmp.dir.createDirPath(io, "src");
    try tmp.dir.writeFile(io, .{
        .sub_path = "src/parser.c",
        .data = "void *tree_sitter_fake(void) { return 0; }\n",
    });

    const out = try std.fmt.allocPrint(gpa, "{s}/fake.{s}", .{ dir, sharedLibExt() });
    defer gpa.free(out);

    try build(io, gpa, dir, out);
    try Io.Dir.cwd().access(io, out, .{});

    // Present but returning null: the load path must report that as a missing
    // symbol rather than handing back a null language to crash on later.
    try testing.expectError(Error.SymbolNotFound, load(gpa, out, "tree_sitter_fake"));
    try testing.expectError(Error.SymbolNotFound, load(gpa, out, "tree_sitter_absent"));

    // Second build is a no-op: the artefact is newer than the source.
    try build(io, gpa, dir, out);
}

test "a source tree with no parser.c is refused, not compiled into nothing" {
    const gpa = testing.allocator;
    var t: std.Io.Threaded = .init(gpa, .{});
    defer t.deinit();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const dir = buf[0..try tmp.dir.realPath(t.io(), &buf)];
    const out = try std.fmt.allocPrint(gpa, "{s}/none.{s}", .{ dir, sharedLibExt() });
    defer gpa.free(out);

    try testing.expectError(Error.ParserSourceMissing, build(t.io(), gpa, dir, out));
}

test "cloning is hermetic, idempotent, and leaves no lock behind" {
    // A local source repo rather than the network: git clones a path just as
    // happily as a URL, so the lock, the re-check and the failure path are all
    // exercised without leaving the machine.
    const gpa = testing.allocator;
    var t: std.Io.Threaded = .init(gpa, .{});
    defer t.deinit();
    const io = t.io();
    const cwd = Io.Dir.cwd();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const base = buf[0..try tmp.dir.realPath(io, &buf)];

    const src = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-fake", .{base});
    defer gpa.free(src);
    try cwd.createDirPath(io, src);
    const readme = try std.fmt.allocPrint(gpa, "{s}/README", .{src});
    defer gpa.free(readme);
    try cwd.writeFile(io, .{ .sub_path = readme, .data = "x" });
    for ([_][]const []const u8{
        &.{ "git", "init", "-q", src },
        &.{ "git", "-C", src, "add", "-A" },
        &.{ "git", "-C", src, "-c", "user.email=t@e", "-c", "user.name=t", "commit", "-qm", "x" },
    }) |argv| {
        const r = try process.run(io, gpa, argv, .{});
        defer r.deinit(gpa);
        if (!r.ok()) return error.SkipZigTest; // no usable git here
    }

    const parent = try std.fmt.allocPrint(gpa, "{s}/repos", .{base});
    defer gpa.free(parent);

    const first = try ensureCloned(io, gpa, src, parent, 5);
    defer gpa.free(first);
    try cwd.access(io, first, .{});
    try testing.expect(std.mem.endsWith(u8, first, "tree-sitter-fake"));

    // The lock is released, not left for the next process to time out on.
    const lock = try std.fmt.allocPrint(gpa, "{s}.lock", .{first});
    defer gpa.free(lock);
    try testing.expectError(error.FileNotFound, cwd.access(io, lock, .{}));

    // Second call is a no-op that returns the same directory.
    const second = try ensureCloned(io, gpa, src, parent, 5);
    defer gpa.free(second);
    try testing.expectEqualStrings(first, second);
}

test "a clone that fails reports it rather than leaving a half-built directory" {
    const gpa = testing.allocator;
    var t: std.Io.Threaded = .init(gpa, .{});
    defer t.deinit();
    const io = t.io();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const base = buf[0..try tmp.dir.realPath(io, &buf)];
    const parent = try std.fmt.allocPrint(gpa, "{s}/repos", .{base});
    defer gpa.free(parent);

    const missing = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-absent", .{base});
    defer gpa.free(missing);

    try testing.expectError(Error.CloneFailed, ensureCloned(io, gpa, missing, parent, 5));
    const left = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-absent", .{parent});
    defer gpa.free(left);
    try testing.expectError(error.FileNotFound, Io.Dir.cwd().access(io, left, .{}));
}
