//! Grammar preparation: from a registry entry to a loaded `TSLanguage`.
//!
//! Replaces what `synapse-tags.sh` delegated to the tree-sitter CLI and to
//! `git`. The steps are the same ones the script performed -- clone the
//! grammar repo on first use, under a lock, into the grammars directory --
//! plus the one the CLI used to do invisibly: compile the parser. Doing it
//! ourselves is what removes the CLI, and with it Node.
//!
//! A C compiler is still required at runtime, and that is not a regression to
//! apologise for so much as a fact to state: a grammar cloned at runtime has
//! to be compiled by something, and this binary is not a compiler. `zig cc` is
//! preferred where Zig is installed, since it is the same toolchain the binary
//! was built with; `cc`, `gcc` and `clang` follow, which is the same set the
//! shell script accepted. Each is tried for real, not asked whether it exists
//! -- a driver that answers `--version` and then cannot compile is a live
//! configuration, and the first candidate failing is not evidence that the
//! grammar cannot be built here.

const std = @import("std");
const root = @import("root.zig");
const process = @import("adapters").process;

const c = root.c;
const Io = std.Io;
const Allocator = std.mem.Allocator;

/// The one place ~60s at 200ms a try (matching the shell script's own
/// default) is a number instead of a name. `Extractor.lock_tries`'s own
/// field default and every `SYNAPSE_GRAMMAR_LOCK_TRIES`-parse-failure
/// fallback (`tags.zig`, `vocab_cmd.zig`, `tags_cache_cmd.zig`) reference
/// this constant rather than repeating `300` -- five independent literals
/// that happened to agree is exactly the kind of drift a shared name
/// closes off. `build`'s own two callers pass it too, for `max_tries`.
pub const default_lock_tries: usize = 300;

pub const Error = error{
    NoCompiler,
    CloneFailed,
    CompileFailed,
    ParserSourceMissing,
    SymbolNotFound,
    /// The grammar was generated by a newer tree-sitter than the pinned
    /// libtree-sitter understands. Reported rather than crashed on, because
    /// `ts_parser_set_language` would otherwise just refuse with no reason.
    AbiUnsupported,
};

/// `tree-sitter-java` -> `tree_sitter_java`. Derived from the repo name, the
/// way the CLI derives it, which is right for every grammar whose repo holds
/// exactly one language. A repo shipping two (tree-sitter-typescript, with
/// `typescript` and `tsx`) will need the registry entry to name the symbol
/// explicitly; nothing here guesses a second one.
pub fn symbolFor(gpa: Allocator, repo_name: []const u8) ![]u8 {
    const stem = if (std.mem.startsWith(u8, repo_name, "tree-sitter-"))
        repo_name["tree-sitter-".len..]
    else
        repo_name;
    const out = try gpa.alloc(u8, "tree_sitter_".len + stem.len);
    @memcpy(out[0.."tree_sitter_".len], "tree_sitter_");
    for (stem, 0..) |ch, i| out["tree_sitter_".len + i] = if (ch == '-') '_' else ch;
    return out;
}

/// The platform's shared-library extension. Grammars are loaded with
/// `std.DynLib`, which is `dlopen` on POSIX and `LoadLibrary` on Windows, so
/// the only per-platform detail is the file name.
pub fn sharedLibExt() []const u8 {
    return switch (@import("builtin").os.tag) {
        .windows => "dll",
        .macos, .ios, .watchos, .tvos => "dylib",
        else => "so",
    };
}

/// `basename` of a git URL with any `.git` suffix removed, matching the
/// script's `basename "$repo" .git`.
pub fn repoNameOf(url: []const u8) []const u8 {
    const trimmed = std.mem.trimEnd(u8, url, "/");
    const base = std.fs.path.basename(trimmed);
    return if (std.mem.endsWith(u8, base, ".git")) base[0 .. base.len - ".git".len] else base;
}

pub const Compiler = struct {
    argv0: []const u8,
    /// `cc` for zig, nothing for a compiler that is one already.
    sub: ?[]const u8,

    /// What to call it in a message: `zig cc`, or just `clang`.
    pub fn label(self: Compiler, gpa: Allocator) ![]u8 {
        return if (self.sub) |s|
            std.fmt.allocPrint(gpa, "{s} {s}", .{ self.argv0, s })
        else
            gpa.dupe(u8, self.argv0);
    }
};

/// In preference order, and every one of them is tried for real before the
/// build gives up.
///
/// `zig cc` first: it is the same toolchain this binary was built with, it
/// cross-compiles, and on a machine that installed synapse from source it is
/// already there. The other three are what `synapse-tags.sh` accepted, and
/// dropping two of them when it was ported was a quiet narrowing -- one this
/// list restores.
pub const compilers = [_]Compiler{
    .{ .argv0 = "zig", .sub = "cc" },
    .{ .argv0 = "cc", .sub = null },
    .{ .argv0 = "gcc", .sub = null },
    .{ .argv0 = "clang", .sub = null },
};

/// The first candidate that is on PATH at all. A precondition check, not a
/// promise that it works -- see `build`, which finds that out the only way it
/// can be found out.
pub fn findCompiler(io: Io, gpa: Allocator) !Compiler {
    for (compilers) |candidate| {
        const version_arg = if (candidate.sub != null) "version" else "--version";
        if (probe(io, gpa, &.{ candidate.argv0, version_arg })) return candidate;
    }
    return Error.NoCompiler;
}

/// Whether the command exists and exits 0. Deliberately not treated as
/// evidence that it can compile: on a GitHub `ubuntu-latest` runner, `cc
/// --version` succeeds and `cc` then dies with `cannot execute 'cc1'`,
/// because the driver is installed and its backend is not. That is what a
/// version probe cannot see, and why it decides only the *order* things are
/// tried in, never which one is used.
fn probe(io: Io, gpa: Allocator, argv: []const []const u8) bool {
    const res = process.run(io, gpa, argv, .{}) catch return false;
    defer res.deinit(gpa);
    return res.ok();
}

/// Build `repo_dir/src/parser.c` (plus `scanner.c` when present) into
/// `out_path`. Returns silently if `out_path` is already newer than the
/// sources -- a grammar is compiled once and reused, exactly as the CLI's own
/// build cache behaved.
///
/// `max_tries` (sb-013) bounds the compile lock's wait the same way
/// `ensureCloned`'s own parameter bounds its clone lock -- both callers pass
/// `default_lock_tries` today (unlike the clone lock, this one is not yet
/// wired to `SYNAPSE_GRAMMAR_LOCK_TRIES`; a real improvement, kept separate
/// from the race this parameter exists to close). Threaded through mainly so
/// a test can pass a small value and observe a timeout without a real wait.
pub fn build(io: Io, gpa: Allocator, repo_dir: []const u8, out_path: []const u8, max_tries: usize) !void {
    const cwd = Io.Dir.cwd();

    const parser_c = try std.fs.path.join(gpa, &.{ repo_dir, "src", "parser.c" });
    defer gpa.free(parser_c);
    cwd.access(io, parser_c, .{}) catch return Error.ParserSourceMissing;

    // Every source that goes into the link, collected before the up-to-date
    // check rather than after it, because each one of them is a reason the
    // artefact could be out of date.
    var sources: std.ArrayListUnmanaged([]const u8) = .empty;
    defer sources.deinit(gpa);
    try sources.append(gpa, parser_c);

    // Some grammars carry an external scanner. C is common (python, kotlin);
    // C++ (`scanner.cc`) exists too and would need `zig c++` plus libc++, so
    // it is refused loudly rather than compiled into a link error.
    const scanner_c = try std.fs.path.join(gpa, &.{ repo_dir, "src", "scanner.c" });
    defer gpa.free(scanner_c);
    const scanner_cc = try std.fs.path.join(gpa, &.{ repo_dir, "src", "scanner.cc" });
    defer gpa.free(scanner_cc);
    if (cwd.access(io, scanner_c, .{})) |_| {
        try sources.append(gpa, scanner_c);
    } else |_| if (cwd.access(io, scanner_cc, .{})) |_| {
        std.debug.print(
            "synapse: {s} has a C++ scanner, which is not supported yet -- skipping that grammar\n",
            .{repo_dir},
        );
        return Error.CompileFailed;
    } else |_| {}

    if (try upToDate(io, out_path, sources.items)) return;

    // Locked from here on (sb-013): two threads needing the same
    // not-yet-built extension for the first time in one run can both reach
    // this point for the identical `out_path` -- `vocab_cmd.zig`'s parallel
    // `Worker`s each carry their own `Extractor`/grammar cache, so nothing
    // upstream of this function already serializes them, and without a
    // lock both would invoke the compiler concurrently against the same
    // output file, with `dlopen` racing a possibly-truncated result. Same
    // discipline as `ensureCloned`'s own clone lock -- see its docstring
    // for the reasoning this mirrors: a directory at `{out_path}.lock`,
    // staleness takeover after the same window, a bounded wait. A separate
    // lock from the clone one on purpose: compiling and cloning are
    // different resources with different callers, and serializing a fast
    // in-process compile behind a network-clone-sized wait would be its
    // own bug. `max_tries` is this function's own parameter, not yet wired
    // to `SYNAPSE_GRAMMAR_LOCK_TRIES` the way the clone lock's is -- both
    // current callers pass `default_lock_tries`; a real user-facing
    // improvement, kept separate from the race this closes.
    const compile_lock_dir = try std.fmt.allocPrint(gpa, "{s}.lock", .{out_path});
    defer gpa.free(compile_lock_dir);

    var got_compile_lock = false;
    var compile_tries: usize = 0;
    while (compile_tries < max_tries) : (compile_tries += 1) {
        if (cwd.createDir(io, compile_lock_dir, .default_dir)) |_| {
            got_compile_lock = true;
            break;
        } else |_| {}
        // Another thread may have finished and released between our check
        // above and this attempt.
        if (try upToDate(io, out_path, sources.items)) return;
        if (lockAbandoned(io, compile_lock_dir)) {
            cwd.deleteDir(io, compile_lock_dir) catch {};
            if (cwd.createDir(io, compile_lock_dir, .default_dir)) |_| {
                got_compile_lock = true;
                break;
            } else |_| {}
        }
        std.Io.sleep(io, .fromMilliseconds(200), .awake) catch {};
    }

    if (!got_compile_lock) {
        std.debug.print(
            "synapse: timed out waiting for the compile lock {s} -- another synapse is compiling " ++
                "this grammar, or one was killed within the last {d} minutes; a lock left by a " ++
                "crash is taken over automatically once it is older than that\n",
            .{ compile_lock_dir, @divTrunc(lock_stale_after_ns, std.time.ns_per_min) },
        );
        return Error.CompileFailed;
    }
    defer cwd.deleteDir(io, compile_lock_dir) catch {};

    // Re-check under the lock: another thread may have compiled, finished
    // and released between our last look and our acquiring it.
    if (try upToDate(io, out_path, sources.items)) return;

    const src_dir = try std.fs.path.join(gpa, &.{ repo_dir, "src" });
    defer gpa.free(src_dir);
    const include = try std.fmt.allocPrint(gpa, "-I{s}", .{src_dir});
    defer gpa.free(include);

    // -fPIC and -shared are what make it loadable; -O2 because a parser is
    // hot and this is paid once. No -march=native: the artefact is cached on
    // disk and may outlive the machine that built it.
    var argv: std.ArrayListUnmanaged([]const u8) = .empty;
    defer argv.deinit(gpa);
    try argv.appendSlice(gpa, &.{ "-shared", "-fPIC", "-O2", include, "-o", out_path });
    try argv.appendSlice(gpa, sources.items);

    if (std.fs.path.dirname(out_path)) |dir| cwd.createDirPath(io, dir) catch {};

    // Every candidate that is present gets a real attempt, and the failures
    // are collected rather than the first one being reported as the answer.
    // A driver that runs but cannot compile is a real configuration -- see
    // `probe` -- so "the first compiler on PATH failed" is not the same
    // statement as "this grammar cannot be built here", and only the second
    // one is worth giving up on.
    var report: std.Io.Writer.Allocating = .init(gpa);
    defer report.deinit();
    var tried: usize = 0;

    for (compilers) |candidate| {
        const version_arg = if (candidate.sub != null) "version" else "--version";
        if (!probe(io, gpa, &.{ candidate.argv0, version_arg })) continue;
        tried += 1;

        var full: std.ArrayListUnmanaged([]const u8) = .empty;
        defer full.deinit(gpa);
        try full.append(gpa, candidate.argv0);
        if (candidate.sub) |s| try full.append(gpa, s);
        try full.appendSlice(gpa, argv.items);

        const res = try process.run(io, gpa, full.items, .{});
        defer res.deinit(gpa);
        if (res.ok()) return;

        const name = try candidate.label(gpa);
        defer gpa.free(name);
        try report.writer.print("  {s}: {s}\n", .{ name, std.mem.trimEnd(u8, res.stderr, "\n") });
    }

    if (tried == 0) return Error.NoCompiler;
    std.debug.print("synapse: compiling {s} failed with every compiler found:\n{s}", .{
        repo_dir, report.written(),
    });
    return Error.CompileFailed;
}

/// Whether the artefact is newer than *every* source that goes into it.
///
/// Every source, not just `parser.c`. A grammar with an external scanner links
/// `scanner.c` as well, and that file changes on its own -- a grammar repo is
/// regenerated as a unit, but `git pull` sets mtimes per file, so a scanner fix
/// with no parser change is an ordinary event rather than a contrived one.
/// Checking the parser alone called that up to date and reused a shared object
/// built from the previous scanner, which is the failure mode a build cache is
/// supposed to be too boring to have: silent, and wrong only in the parse.
fn upToDate(io: Io, out_path: []const u8, sources: []const []const u8) !bool {
    const cwd = Io.Dir.cwd();
    const out = cwd.statFile(io, out_path, .{}) catch return false;
    for (sources) |source| {
        const src = cwd.statFile(io, source, .{}) catch return false;
        if (out.mtime.nanoseconds < src.mtime.nanoseconds) return false;
    }
    return true;
}

/// Clone a grammar repo on first use, into `repos_parent/<name>`, and return
/// that directory. Already present means nothing to do.
///
/// The lock is not belt-and-braces. Callers tag in parallel chunks, and each
/// worker runs this same readiness check independently: without it, two
/// workers seeing the same missing directory both start a clone, git refuses
/// the second because the destination is not empty, and that worker's failure
/// path removes the directory out from under the first one's still-running
/// clone. `createDir` is atomic across processes on a POSIX filesystem, so
/// exactly one worker wins and the rest wait for it rather than racing a
/// second clone in.
///
/// A lock is honoured while it could belong to a live holder, and taken over
/// once it could not -- see `lock_stale_after_ns`. That distinction is the whole
/// of the change from honouring any lock that exists: a process killed mid-clone
/// left one behind with nothing to remove it, so every later run paid the full
/// wait and then skipped that grammar, for good. Taking over an aged lock is
/// safe rather than merely probably-safe, because `cloneInto` publishes by
/// rename -- the worst case is two clones, one of them wasted, never a damaged
/// one.
pub fn ensureCloned(
    io: Io,
    gpa: Allocator,
    repo_url: []const u8,
    repos_parent: []const u8,
    max_tries: usize,
) ![]u8 {
    const cwd = Io.Dir.cwd();
    const repo_dir = try std.fs.path.join(gpa, &.{ repos_parent, repoNameOf(repo_url) });
    errdefer gpa.free(repo_dir);

    if (cwd.access(io, repo_dir, .{})) |_| return repo_dir else |_| {}

    try cwd.createDirPath(io, repos_parent);

    const lock_dir = try std.fmt.allocPrint(gpa, "{s}.lock", .{repo_dir});
    defer gpa.free(lock_dir);

    var got_lock = false;
    var tries: usize = 0;
    while (tries < max_tries) : (tries += 1) {
        if (cwd.createDir(io, lock_dir, .default_dir)) |_| {
            got_lock = true;
            break;
        } else |_| {}
        // The holder may have finished and released between our check above
        // and this attempt, in which case there is nothing left to wait for.
        if (cwd.access(io, repo_dir, .{})) |_| break else |_| {}

        // An abandoned lock is not a held one. The policy below is unchanged --
        // never take a lock that could belong to a live holder -- and this is
        // only what "could" means: `exists` was the test, and a process killed
        // mid-clone made that permanently true with nobody behind it.
        if (lockAbandoned(io, lock_dir)) {
            cwd.deleteDir(io, lock_dir) catch {};
            if (cwd.createDir(io, lock_dir, .default_dir)) |_| {
                got_lock = true;
                break;
            } else |_| {}
        }
        std.Io.sleep(io, .fromMilliseconds(200), .awake) catch {};
    }

    if (got_lock) {
        defer cwd.deleteDir(io, lock_dir) catch {};
        // Re-check under the lock: a worker may have cloned, finished and
        // released between our last look and our acquiring it.
        if (cwd.access(io, repo_dir, .{})) |_| return repo_dir else |_| {}

        try cloneInto(io, gpa, repo_url, repo_dir);
        return repo_dir;
    }

    // Never got the lock, it was not old enough to be abandoned, and the
    // directory still is not there. So something is holding it and has held it
    // for less than `lock_stale_after`: either a live clone slower than this
    // ceiling, or a crash too recent to have aged out yet. Refusing is right in
    // both cases -- a waiter that timed out does not own the lock, and racing a
    // clone against a merely slow holder wastes a full clone.
    //
    // Naming the lock is the point of the message. The failure the caller
    // reports is `CloneFailed`, which reads as a network problem; without the
    // path there is nothing here a person can act on, and the whole condition
    // is a directory waiting to be removed.
    cwd.access(io, repo_dir, .{}) catch {
        std.debug.print(
            "synapse: timed out waiting for the grammar lock {s} -- another synapse is cloning, " ++
                "or one was killed within the last {d} minutes; a lock left by a crash is taken " ++
                "over automatically once it is older than that\n",
            .{ lock_dir, @divTrunc(lock_stale_after_ns, std.time.ns_per_min) },
        );
        return Error.CloneFailed;
    };
    return repo_dir;
}

/// How long a lock must go untouched before it counts as abandoned rather than
/// held.
///
/// A `--depth 1` clone of a grammar repo is a few megabytes -- tree-sitter-python
/// is 4.5 MB -- so nothing legitimate is still inside one fifteen minutes later.
/// It is also well clear of the ~60s a waiter spends before giving up, which
/// matters: a lock this old has already outlived every waiter that honoured it,
/// so honouring it further protects nobody.
pub const lock_stale_after_ns: i96 = 15 * std.time.ns_per_min;

/// Whether the lock has gone untouched long enough to be treated as abandoned.
///
/// Anything unreadable is "not abandoned": a lock that vanished between the
/// failed acquire and this stat is not ours to reason about, and the next
/// iteration will simply take it.
///
/// The wall clock rather than the monotonic one, because it is compared against
/// an mtime. A clock stepped backwards makes this return false and costs a wait;
/// stepped forwards, it takes a lock early -- which is bounded by the same thing
/// every other duplicate clone is, one wasted clone, since publication is by
/// rename.
fn lockAbandoned(io: Io, lock_dir: []const u8) bool {
    const st = Io.Dir.cwd().statFile(io, lock_dir, .{}) catch return false;
    const now = Io.Timestamp.now(io, .real).nanoseconds;
    return now - st.mtime.nanoseconds > lock_stale_after_ns;
}

/// Clone into a private staging directory and publish it with one rename.
///
/// `git clone <dst>` builds its destination in place, so an interrupted clone --
/// a SIGKILL, a full disk, a laptop closing -- leaves a directory that exists
/// and is not a repository. Existence was the readiness test, so the next run
/// adopted that directory; `build` then refused it for having no `src/parser.c`
/// and kept refusing it, because nothing removed it and nothing re-cloned. Loud,
/// but permanent, and the error named the wrong problem.
///
/// Rename is atomic on POSIX, so publishing through one makes the destination's
/// existence mean the clone finished -- which is the property the readiness test
/// was assuming all along. It also makes a duplicate clone harmless, which is
/// what lets the lock be an optimization rather than the thing correctness rests
/// on: the staging path carries the clock, so two attempts never share one, and
/// a rename onto a directory another clone already published fails rather than
/// merging into it.
fn cloneInto(io: Io, gpa: Allocator, repo_url: []const u8, repo_dir: []const u8) !void {
    const cwd = Io.Dir.cwd();

    const staged = try std.fmt.allocPrint(gpa, "{s}.partial.{d}", .{
        repo_dir, Io.Timestamp.now(io, .awake).nanoseconds,
    });
    defer gpa.free(staged);

    const res = try process.run(io, gpa, &.{ "git", "clone", "--depth", "1", "-q", repo_url, staged }, .{});
    defer res.deinit(gpa);
    if (!res.ok()) {
        cwd.deleteTree(io, staged) catch {};
        return Error.CloneFailed;
    }

    cwd.rename(staged, cwd, repo_dir, io) catch {
        // Losing the rename is the ordinary way two clones of one grammar end.
        // The winner's copy is as good as ours, so this is a success with a
        // staging directory to sweep up -- unless nothing is there at all, in
        // which case the rename failed for its own reasons and we have not
        // produced the grammar we claimed to.
        cwd.deleteTree(io, staged) catch {};
        cwd.access(io, repo_dir, .{}) catch return Error.CloneFailed;
    };
}

/// Load a built grammar and hand back its language, refusing an ABI the pinned
/// libtree-sitter cannot parse with rather than letting the failure surface
/// later as an unexplained parse of nothing.
pub fn load(gpa: Allocator, lib_path: []const u8, symbol: []const u8) !*const c.TSLanguage {
    var lib = try std.DynLib.open(lib_path);
    // Deliberately not closed: the returned TSLanguage points into this image,
    // and every caller keeps using it for the life of the process. Closing
    // here is a use-after-free that only shows up under load.
    const sym = try gpa.dupeZ(u8, symbol);
    defer gpa.free(sym);

    const LangFn = *const fn () callconv(.c) ?*const c.TSLanguage;
    const fn_ptr = lib.lookup(LangFn, sym) orelse return Error.SymbolNotFound;
    const lang = fn_ptr() orelse return Error.SymbolNotFound;

    const abi = c.ts_language_abi_version(lang);
    if (abi < root.abi_min or abi > root.abi_max) return Error.AbiUnsupported;
    return lang;
}

const testing = std.testing;

test "symbol names are derived the way the CLI derives them" {
    const gpa = testing.allocator;
    const java = try symbolFor(gpa, "tree-sitter-java");
    defer gpa.free(java);
    try testing.expectEqualStrings("tree_sitter_java", java);

    // Hyphens inside the language name become underscores, or dlsym misses.
    const embedded = try symbolFor(gpa, "tree-sitter-embedded-template");
    defer gpa.free(embedded);
    try testing.expectEqualStrings("tree_sitter_embedded_template", embedded);
}

test "repo names come off a URL with or without .git" {
    try testing.expectEqualStrings("tree-sitter-java", repoNameOf("https://github.com/tree-sitter/tree-sitter-java"));
    try testing.expectEqualStrings("tree-sitter-java", repoNameOf("https://github.com/tree-sitter/tree-sitter-java.git"));
    try testing.expectEqualStrings("tree-sitter-java", repoNameOf("git@github.com:tree-sitter/tree-sitter-java.git"));
}

test "a compiler is found on this machine" {
    const found = try findCompiler(testing.io, testing.allocator);
    try testing.expect(found.argv0.len > 0);
}

test "end to end: compile a source tree and load a symbol out of it" {
    // A stand-in grammar rather than a real one: it exercises compiler
    // discovery, argv construction, the spawn, the up-to-date short-circuit,
    // DynLib open and symbol lookup, without needing the network or whatever
    // happens to be in the developer's grammar cache. The real grammars are
    // covered by the differential against the tree-sitter CLI.
    const gpa = testing.allocator;
    const io = testing.io;

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const dir = buf[0..try tmp.dir.realPath(io, &buf)];

    try tmp.dir.createDirPath(io, "src");
    try tmp.dir.writeFile(io, .{
        .sub_path = "src/parser.c",
        .data = "void *tree_sitter_fake(void) { return 0; }\n",
    });

    const out = try std.fmt.allocPrint(gpa, "{s}/fake.{s}", .{ dir, sharedLibExt() });
    defer gpa.free(out);

    try build(io, gpa, dir, out, default_lock_tries);
    try Io.Dir.cwd().access(io, out, .{});

    // Present but returning null: the load path must report that as a missing
    // symbol rather than handing back a null language to crash on later.
    try testing.expectError(Error.SymbolNotFound, load(gpa, out, "tree_sitter_fake"));
    try testing.expectError(Error.SymbolNotFound, load(gpa, out, "tree_sitter_absent"));

    // Second build is a no-op: the artefact is newer than the source.
    try build(io, gpa, dir, out, default_lock_tries);
}

test "a scanner newer than the artefact rebuilds it, the way a newer parser does" {
    const gpa = testing.allocator;
    const io = testing.io;
    const cwd = Io.Dir.cwd();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const dir = buf[0..try tmp.dir.realPath(io, &buf)];

    try tmp.dir.createDirPath(io, "src");
    try tmp.dir.writeFile(io, .{
        .sub_path = "src/parser.c",
        .data = "void *tree_sitter_fake(void) { return 0; }\n",
    });
    try tmp.dir.writeFile(io, .{
        .sub_path = "src/scanner.c",
        .data = "int fake_scan(void) { return 1; }\n",
    });

    const out = try std.fmt.allocPrint(gpa, "{s}/scan.{s}", .{ dir, sharedLibExt() });
    defer gpa.free(out);

    try build(io, gpa, dir, out, default_lock_tries);
    const built_at = (try cwd.statFile(io, out, .{})).mtime.nanoseconds;

    // Control: with a scanner present and nothing touched, the short-circuit
    // still holds. Without this the test below would pass on a build that had
    // simply stopped caching.
    try build(io, gpa, dir, out, default_lock_tries);
    try testing.expectEqual(built_at, (try cwd.statFile(io, out, .{})).mtime.nanoseconds);

    // Only the scanner moves, and it moves to a second *after* the artefact --
    // set rather than slept for, so the assertion does not rest on filesystem
    // timestamp granularity. `parser.c` stays older than the artefact, which is
    // what makes this isolate the scanner: checking the parser alone reported
    // this grammar up to date and reused a shared object built from the
    // previous scanner.
    const scanner = try std.fs.path.join(gpa, &.{ dir, "src", "scanner.c" });
    defer gpa.free(scanner);
    {
        const f = try cwd.openFile(io, scanner, .{ .mode = .read_write });
        defer f.close(io);
        try f.setTimestamps(io, .{
            .modify_timestamp = .{ .new = .{ .nanoseconds = built_at + std.time.ns_per_s } },
        });
    }

    try build(io, gpa, dir, out, default_lock_tries);
    try testing.expect((try cwd.statFile(io, out, .{})).mtime.nanoseconds > built_at);
}

test "a source tree with no parser.c is refused, not compiled into nothing" {
    const gpa = testing.allocator;

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const dir = buf[0..try tmp.dir.realPath(testing.io, &buf)];
    const out = try std.fmt.allocPrint(gpa, "{s}/none.{s}", .{ dir, sharedLibExt() });
    defer gpa.free(out);

    try testing.expectError(Error.ParserSourceMissing, build(testing.io, gpa, dir, out, default_lock_tries));
}

/// A local git repository to clone from. `git clone` takes a path as happily as
/// a URL, so the lock, the staging directory and the failure path are all
/// exercised without leaving the machine. `error.SkipZigTest` where there is no
/// usable git.
fn stageSourceRepo(io: Io, gpa: Allocator, base: []const u8) ![]u8 {
    const cwd = Io.Dir.cwd();
    const src = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-fake", .{base});
    errdefer gpa.free(src);
    try cwd.createDirPath(io, src);

    const readme = try std.fmt.allocPrint(gpa, "{s}/README", .{src});
    defer gpa.free(readme);
    try cwd.writeFile(io, .{ .sub_path = readme, .data = "x" });

    for ([_][]const []const u8{
        &.{ "git", "init", "-q", src },
        &.{ "git", "-C", src, "add", "-A" },
        &.{ "git", "-C", src, "-c", "user.email=t@e", "-c", "user.name=t", "commit", "-qm", "x" },
    }) |argv| {
        const r = try process.run(io, gpa, argv, .{});
        defer r.deinit(gpa);
        if (!r.ok()) return error.SkipZigTest;
    }
    return src;
}

test "cloning is hermetic, idempotent, and leaves no lock behind" {
    const gpa = testing.allocator;
    const io = testing.io;
    const cwd = Io.Dir.cwd();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const base = buf[0..try tmp.dir.realPath(io, &buf)];

    const src = try stageSourceRepo(io, gpa, base);
    defer gpa.free(src);

    const parent = try std.fmt.allocPrint(gpa, "{s}/repos", .{base});
    defer gpa.free(parent);

    const first = try ensureCloned(io, gpa, src, parent, 5);
    defer gpa.free(first);
    try cwd.access(io, first, .{});
    try testing.expect(std.mem.endsWith(u8, first, "tree-sitter-fake"));

    // The lock is released, not left for the next process to time out on.
    const lock = try std.fmt.allocPrint(gpa, "{s}.lock", .{first});
    defer gpa.free(lock);
    try testing.expectError(error.FileNotFound, cwd.access(io, lock, .{}));

    // Second call is a no-op that returns the same directory.
    const second = try ensureCloned(io, gpa, src, parent, 5);
    defer gpa.free(second);
    try testing.expectEqualStrings(first, second);

    // Nothing staged is left next to it. The clone lands in a private directory
    // and is published by rename, so a leftover here would mean the rename did
    // not happen and the destination is something else's.
    var dir = try Io.Dir.cwd().openDir(io, parent, .{ .iterate = true });
    defer dir.close(io);
    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        try testing.expect(std.mem.indexOf(u8, entry.name, ".partial") == null);
    }
}

test "a lock older than the staleness window is taken over, a fresh one is not" {
    const gpa = testing.allocator;
    const io = testing.io;
    const cwd = Io.Dir.cwd();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const base = buf[0..try tmp.dir.realPath(io, &buf)];

    const src = try stageSourceRepo(io, gpa, base);
    defer gpa.free(src);

    const parent = try std.fmt.allocPrint(gpa, "{s}/repos", .{base});
    defer gpa.free(parent);
    try cwd.createDirPath(io, parent);
    const lock = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-fake.lock", .{parent});
    defer gpa.free(lock);

    // Fresh: it could belong to a live holder, so the wait times out and refuses.
    // This is the case tests/synapse-tags.bats also pins, and the policy it pins
    // is the one being kept.
    try cwd.createDirPath(io, lock);
    try testing.expectError(Error.CloneFailed, ensureCloned(io, gpa, src, parent, 2));
    try cwd.access(io, lock, .{}); // and a waiter that timed out did not delete it

    // Aged past the window: nobody is behind it, so it is taken over rather than
    // waited on. Set rather than slept for -- fifteen minutes is not a test.
    const long_ago = Io.Timestamp.now(io, .real).nanoseconds - lock_stale_after_ns - std.time.ns_per_min;
    try cwd.setTimestamps(io, lock, .{ .modify_timestamp = .{ .new = .{ .nanoseconds = long_ago } } });

    const dir = try ensureCloned(io, gpa, src, parent, 2);
    defer gpa.free(dir);

    // A real clone, not an empty directory that merely exists.
    const readme = try std.fmt.allocPrint(gpa, "{s}/README", .{dir});
    defer gpa.free(readme);
    try cwd.access(io, readme, .{});

    // And the taken-over lock is released like any other.
    try testing.expectError(error.FileNotFound, cwd.access(io, lock, .{}));
}

test "compiling is locked the same way cloning is: a fresh lock refuses, a stale one is taken over" {
    const gpa = testing.allocator;
    const io = testing.io;
    const cwd = Io.Dir.cwd();

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const dir = buf[0..try tmp.dir.realPath(io, &buf)];

    try tmp.dir.createDirPath(io, "src");
    try tmp.dir.writeFile(io, .{
        .sub_path = "src/parser.c",
        .data = "void *tree_sitter_fake(void) { return 0; }\n",
    });

    const out = try std.fmt.allocPrint(gpa, "{s}/locked.{s}", .{ dir, sharedLibExt() });
    defer gpa.free(out);
    const lock = try std.fmt.allocPrint(gpa, "{s}.lock", .{out});
    defer gpa.free(lock);

    // Fresh: it could belong to a live compile, so the wait times out and
    // refuses rather than compiling out from under the holder.
    try cwd.createDirPath(io, lock);
    try testing.expectError(Error.CompileFailed, build(io, gpa, dir, out, 2));
    try cwd.access(io, lock, .{}); // a waiter that timed out did not delete it
    try testing.expectError(error.FileNotFound, cwd.access(io, out, .{}));

    // Aged past the window: nobody is behind it, so it is taken over and the
    // compile proceeds. Set rather than slept for -- fifteen minutes is not a
    // test.
    const long_ago = Io.Timestamp.now(io, .real).nanoseconds - lock_stale_after_ns - std.time.ns_per_min;
    try cwd.setTimestamps(io, lock, .{ .modify_timestamp = .{ .new = .{ .nanoseconds = long_ago } } });

    try build(io, gpa, dir, out, 2);
    try cwd.access(io, out, .{});

    // And the taken-over lock is released like any other.
    try testing.expectError(error.FileNotFound, cwd.access(io, lock, .{}));
}

test "a clone that fails reports it rather than leaving a half-built directory" {
    const gpa = testing.allocator;
    const io = testing.io;

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const base = buf[0..try tmp.dir.realPath(io, &buf)];
    const parent = try std.fmt.allocPrint(gpa, "{s}/repos", .{base});
    defer gpa.free(parent);

    const missing = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-absent", .{base});
    defer gpa.free(missing);

    try testing.expectError(Error.CloneFailed, ensureCloned(io, gpa, missing, parent, 5));
    const left = try std.fmt.allocPrint(gpa, "{s}/tree-sitter-absent", .{parent});
    defer gpa.free(left);
    try testing.expectError(error.FileNotFound, Io.Dir.cwd().access(io, left, .{}));
}
