//! The code profile's Extractor: `tree-sitter tags` behind the port.
//!
//! **This spawns the tree-sitter CLI rather than linking libtree-sitter, and
//! that is a staged decision, not the end state.** Linking would drop `node`,
//! `npm` and `cc` from the runtime — the largest single dependency win
//! available here — but it also means owning the `tree-sitter-tags` semantics
//! ourselves (capture names, name/doc handling, the exact padded output shape)
//! with byte-exactness as the requirement, and it retires the runtime grammar
//! *discovery* the registry exists for: a linked build has a compiled-in set of
//! languages, where today an unknown extension is a prompt to register a new
//! grammar and retry. Both are real changes to what the product is, and
//! neither belongs inside a port that is also trying to preserve behaviour
//! exactly. Spawning keeps `tests/synapse-tags.bats` valid unchanged, since
//! `tests/fixtures/fake-bin/tree-sitter` intercepts a compiled binary exactly
//! as it intercepts the shell script.
//!
//! What this port does remove is the jq spawns: registry resolution, the
//! repo-scoped cache and the tree-sitter config edit are all in-process here.
//!
//! Faithful to `claude/lib/synapse/synapse-tags.sh`, including its exit-code
//! meanings, its one-invocation-per-batch rule, and the single-path output
//! normalisation described below.

const std = @import("std");
const model = @import("model");
const ports = @import("ports");
const tag_line = @import("core").tag_line;

/// libtree-sitter, linked statically from the pinned dependency. Only this
/// module sees it: `core` never does, and neither does `adapters`, which is
/// what keeps a future bard build free of both the library and the C
/// toolchain that grammars need.
pub const c = @cImport({
    @cInclude("tree_sitter/api.h");
});

/// The language ABI range this libtree-sitter accepts. A cloned grammar
/// generated by a newer tree-sitter than the one pinned here is refused with
/// this in the message, rather than crashing inside `ts_parser_set_language`.
pub const abi_min = c.TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION;
pub const abi_max = c.TREE_SITTER_LANGUAGE_VERSION;

pub const grammar = @import("grammar.zig");
pub const tagger = @import("tagger.zig");

const Io = std.Io;
const Allocator = std.mem.Allocator;
const Extractor = ports.Extractor;

/// What the registry can say about one extension. The three cases are the
/// script's three exit codes, and callers act differently on each: `no_entry`
/// is a prompt to run grammar discovery and retry, `unusable` is final.
pub const Readiness = union(enum) {
    /// tree-sitter scope, e.g. `source.java`.
    ready: []const u8,
    /// Registered, but marked `unsupported: true`, or missing repo/scope.
    unusable,
    /// No registry entry at all.
    no_entry,
};

pub const Registry = struct {
    parsed: std.json.Parsed(std.json.Value),

    pub fn load(gpa: Allocator, io: Io, path: []const u8) !Registry {
        const bytes = std.Io.Dir.cwd().readFileAlloc(io, path, gpa, .limited(8 << 20)) catch |e| switch (e) {
            error.FileNotFound => try gpa.dupe(u8, "{}"),
            else => return e,
        };
        defer gpa.free(bytes);
        return .{ .parsed = try std.json.parseFromSlice(std.json.Value, gpa, bytes, .{}) };
    }

    pub fn deinit(self: *Registry) void {
        self.parsed.deinit();
    }

    pub fn lookup(self: Registry, ext: []const u8) Readiness {
        const root = switch (self.parsed.value) {
            .object => |o| o,
            else => return .no_entry,
        };
        const entry = root.get(ext) orelse return .no_entry;
        const obj = switch (entry) {
            .object => |o| o,
            else => return .unusable,
        };
        if (obj.get("unsupported")) |u| {
            if (u == .bool and u.bool) return .unusable;
        }
        const repo = obj.get("repo") orelse return .unusable;
        const scope = obj.get("scope") orelse return .unusable;
        if (repo != .string or scope != .string) return .unusable;
        if (repo.string.len == 0 or scope.string.len == 0) return .unusable;
        return .{ .ready = scope.string };
    }

    /// Every extension with a usable grammar, sorted, deduplicated -- what
    /// `synapse-tags.sh --list-extensions` prints. The registry is the list;
    /// there is deliberately no curated second one to fall out of sync with it.
    pub fn usableExtensions(self: Registry, gpa: Allocator) ![]const []const u8 {
        var out: std.ArrayListUnmanaged([]const u8) = .empty;
        errdefer out.deinit(gpa);
        const root = switch (self.parsed.value) {
            .object => |o| o,
            else => return out.toOwnedSlice(gpa),
        };
        var it = root.iterator();
        while (it.next()) |e| {
            if (self.lookup(e.key_ptr.*) == .ready) try out.append(gpa, e.key_ptr.*);
        }
        const slice = try out.toOwnedSlice(gpa);
        std.mem.sort([]const u8, slice, {}, lessThanBytes);
        return slice;
    }
};

fn lessThanBytes(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.order(u8, a, b) == .lt;
}

/// Lowercased extension, or null when the basename has none. Matches the
/// script's `ext_of`: the dot must not be the whole name, so `Makefile` has no
/// extension and `.gitignore` has none either -- `${base##*.}` equals `$base`
/// only when there is no dot at all, and for `.gitignore` it yields
/// `gitignore`, which is what the awk in batch mode also produces.
pub fn extensionOf(gpa: Allocator, path: []const u8) !?[]u8 {
    const base = std.fs.path.basename(path);
    const dot = std.mem.lastIndexOfScalar(u8, base, '.') orelse return null;
    const ext = base[dot + 1 ..];
    if (ext.len == 0) return null;
    const out = try gpa.alloc(u8, ext.len);
    for (ext, 0..) |ch, i| out[i] = std.ascii.toLower(ch);
    return out;
}

/// Split batch output into per-path outcomes, one per requested path in the
/// same order.
///
/// The shape: an unindented line is a path, and the tab-indented lines under
/// it are that path's tags. A path the CLI could not parse is absent from the
/// output entirely, while one that parsed to nothing still gets its path line
/// -- and that distinction is the whole basis for `unsupported`. Collapsing it
/// would cache a perfectly readable file as unparseable.
pub fn attribute(
    gpa: Allocator,
    raw: []const u8,
    paths: []const []const u8,
) ![]Extractor.Outcome {
    var seen: std.StringHashMapUnmanaged(std.ArrayListUnmanaged(model.Tag)) = .empty;
    defer {
        var it = seen.valueIterator();
        while (it.next()) |v| v.deinit(gpa);
        seen.deinit(gpa);
    }

    var current: ?[]const u8 = null;
    var lines = std.mem.splitScalar(u8, raw, '\n');
    while (lines.next()) |line| {
        if (line.len == 0) continue;
        if (line[0] != '\t') {
            current = line;
            const gop = try seen.getOrPut(gpa, line);
            if (!gop.found_existing) gop.value_ptr.* = .empty;
            continue;
        }
        const path = current orelse continue;
        // The leading tab is batch framing, not content: consumers split on
        // tabs and read field 1 as the symbol name, so leaving it in makes
        // every name empty and every exact-match lookup silently miss.
        const tag = tag_line.parse(line[1..]) orelse continue;
        const gop = try seen.getOrPut(gpa, path);
        if (!gop.found_existing) gop.value_ptr.* = .empty;
        try gop.value_ptr.append(gpa, tag);
    }

    const out = try gpa.alloc(Extractor.Outcome, paths.len);
    errdefer gpa.free(out);
    for (paths, 0..) |p, i| {
        if (seen.getPtr(p)) |tags| {
            out[i] = .{ .tags = try gpa.dupe(model.Tag, tags.items) };
        } else {
            out[i] = .unsupported;
        }
    }
    return out;
}

const testing = std.testing;

test {
    _ = grammar;
    _ = tagger;
}

test "libtree-sitter is linked, and its ABI range covers the grammars in use" {
    // Not a tautology: it fails the day the pinned library stops accepting the
    // language version the registry's grammar repos generate, which is the one
    // way this dependency can break silently.
    try testing.expect(abi_min <= 14 and 14 <= abi_max);
    try testing.expect(c.ts_parser_new() != null);
}

test "registry: ready, unsupported, and absent are three different answers" {
    const json =
        \\{"java":{"repo":"https://x/tree-sitter-java","scope":"source.java"},
        \\ "sh":{"unsupported":true},
        \\ "broken":{"repo":"https://x/y"}}
    ;
    var parsed = try std.json.parseFromSlice(std.json.Value, testing.allocator, json, .{});
    defer parsed.deinit();
    const reg: Registry = .{ .parsed = parsed };

    try testing.expectEqualStrings("source.java", reg.lookup("java").ready);
    try testing.expect(reg.lookup("sh") == .unusable);
    try testing.expect(reg.lookup("broken") == .unusable); // repo without scope
    try testing.expect(reg.lookup("rs") == .no_entry);
}

test "list-extensions is the registry filtered to usable, sorted" {
    const json =
        \\{"py":{"repo":"r","scope":"source.python"},
        \\ "java":{"repo":"r","scope":"source.java"},
        \\ "sh":{"unsupported":true}}
    ;
    var parsed = try std.json.parseFromSlice(std.json.Value, testing.allocator, json, .{});
    defer parsed.deinit();
    const reg: Registry = .{ .parsed = parsed };

    const exts = try reg.usableExtensions(testing.allocator);
    defer testing.allocator.free(exts);
    try testing.expectEqual(@as(usize, 2), exts.len);
    try testing.expectEqualStrings("java", exts[0]);
    try testing.expectEqualStrings("py", exts[1]);
}

test "extensions are lowercased, and a dotless name has none" {
    const gpa = testing.allocator;
    const java = (try extensionOf(gpa, "src/Main.JAVA")).?;
    defer gpa.free(java);
    try testing.expectEqualStrings("java", java);
    try testing.expectEqual(@as(?[]u8, null), try extensionOf(gpa, "Makefile"));
    try testing.expectEqual(@as(?[]u8, null), try extensionOf(gpa, "dir.d/README"));
}

test "attribution: a parsed-empty file keeps its path line, an unparseable one is absent" {
    const raw =
        "a.java\n" ++
        "\tToken     \t | class   \tdef (15, 13) - (15, 18) `public class Token {`\n" ++
        "empty.java\n";

    const out = try attribute(testing.allocator, raw, &.{ "a.java", "empty.java", "gone.bin" });
    defer {
        for (out) |o| if (o == .tags) testing.allocator.free(o.tags);
        testing.allocator.free(out);
    }

    try testing.expectEqual(@as(usize, 1), out[0].tags.len);
    try testing.expectEqualStrings("Token", out[0].tags[0].name);
    try testing.expectEqual(@as(usize, 0), out[1].tags.len); // parsed, nothing in it
    try testing.expect(out[2] == .unsupported); // never appeared
}

test "attribution keeps each path's tags with that path" {
    const raw =
        "a.java\n" ++
        "\tA         \t | class   \tdef (1, 0) - (1, 1) `class A {}`\n" ++
        "b.java\n" ++
        "\tB         \t | class   \tdef (2, 0) - (2, 1) `class B {}`\n" ++
        "\tc         \t | call    \tref (3, 0) - (3, 1) `c();`\n";

    const out = try attribute(testing.allocator, raw, &.{ "a.java", "b.java" });
    defer {
        for (out) |o| if (o == .tags) testing.allocator.free(o.tags);
        testing.allocator.free(out);
    }

    try testing.expectEqual(@as(usize, 1), out[0].tags.len);
    try testing.expectEqualStrings("A", out[0].tags[0].name);
    try testing.expectEqual(@as(usize, 2), out[1].tags.len);
    try testing.expectEqualStrings("B", out[1].tags[0].name);
    try testing.expectEqualStrings("c", out[1].tags[1].name);
}

test "a tag line before any path line is dropped, not attributed to nothing" {
    const raw = "\tOrphan    \t | class   \tdef (1, 0) - (1, 1) `x`\na.java\n";
    const out = try attribute(testing.allocator, raw, &.{"a.java"});
    defer {
        for (out) |o| if (o == .tags) testing.allocator.free(o.tags);
        testing.allocator.free(out);
    }
    try testing.expectEqual(@as(usize, 0), out[0].tags.len);
}
