#!/bin/bash
# Generates docs/cli.md from what the binaries themselves print for --help.
#
# Usage: docs/generate-cli-reference.sh [--check]
#
#   --check  exit 1 if docs/cli.md is out of date, without writing it. Wired into
#            the test suite, so a stale reference fails visibly instead of quietly
#            describing a command that has moved on.
#
# THE SOURCE MOVED, AND SO DID THE GUARANTEE. This replaces
# generate-scripts-reference.sh, which read the header comment block of every
# claude/lib/synapse/*.sh. Those scripts are gone: `synapse` and `synapse-hook`
# are the tooling now. So the source is `--help` itself -- not a comment that
# happens to match it, but the exact bytes a user sees -- which makes the old
# guarantee stronger rather than merely preserved. There is nothing left to keep
# in step.
#
# EVERY --help MUST BE ENVIRONMENT-INDEPENDENT, and that is checked here rather
# than assumed: each one runs under `env -i` from a directory outside any git
# repo, so a subcommand that resolved a namespace or read a conf before answering
# would fail this generator instead of silently baking one machine's paths into a
# committed document. Three did, when this was written -- `index`, `tags` and
# `tags-cache` -- and all three were fixed rather than special-cased.
#
# Exit codes: 0 ok (or up to date), 1 out of date with --check, or a --help that
# failed; 2 usage error
set -euo pipefail

readonly HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT="$(cd "$HERE/.." && pwd)"
readonly OUT="$HERE/cli.md"
readonly SYNAPSE="${SYNAPSE_BIN:-$ROOT/zig-out/bin/synapse}"
readonly HOOK="${SYNAPSE_HOOK_BIN:-$ROOT/zig-out/bin/synapse-hook}"

usage() { # usage [exit-code]
  awk '/^# Usage:/ { p = 1 } p && !/^#/ { exit } p { sub(/^# ?/, ""); print }' "$0" >&2
  exit "${1:-2}"
}

CHECK=false
case "${1:-}" in
  "")        ;;
  --check)   CHECK=true ;;
  -h|--help) usage 0 ;;
  *)         usage ;;
esac

for bin in "$SYNAPSE" "$HOOK"; do
  [ -x "$bin" ] || {
    echo "generate-cli-reference: no binary at $bin -- run 'zig build'" >&2
    exit 1
  }
done

# `env -i` from /tmp: no HOME, no PATH beyond the basics, and nowhere near a git
# repo. A --help that needs any of those is a bug in that subcommand.
help_for() { # help_for <binary> [subcommand...]
  local bin="$1"; shift
  (cd /tmp && env -i PATH=/usr/bin:/bin HOME=/nonexistent "$bin" "$@" --help 2>&1)
}

# CHECKED SEPARATELY FROM RENDERING, and that is not tidiness. `help_for` runs inside
# a command substitution everywhere it is used, so an `exit 1` in there ends the
# subshell and nothing else -- the first version of this script "guarded" that way and
# happily wrote a document with zero subcommands, exiting 0. The check has to run
# where its exit can end the script.
check_help() { # check_help <binary> [subcommand...]
  local bin="$1"
  if ! (cd /tmp && env -i PATH=/usr/bin:/bin HOME=/nonexistent "$@" --help >/dev/null 2>&1); then
    shift
    echo "generate-cli-reference: '$(basename "$bin") $* --help' exited non-zero" >&2
    echo "  every --help must answer without an environment; see this file's header" >&2
    exit 1
  fi
}

validate() {
  check_help "$SYNAPSE"
  check_help "$HOOK"
  local sub
  while read -r sub; do
    [ -n "$sub" ] || continue
    check_help "$SYNAPSE" "$sub"
  done < <(subcommands)
}

subcommands() {
  # The listing in `synapse --help` is the authority on what exists, so a
  # subcommand added without a usage line is a subcommand this reference cannot
  # mention -- which is the right pressure.
  help_for "$SYNAPSE" | sed -n 's/^  \([a-z][a-z-]*\) .*/\1/p' | awk '!seen[$0]++'
}

render() {
  cat <<'EOF'
# CLI reference

Generated by `docs/generate-cli-reference.sh` from what the binaries print for
`--help`. Do not edit by hand; run the generator.

Two binaries. `synapse` is the tooling a person or an agent runs; `synapse-hook`
carries the five Claude Code hooks and is registered in `settings.json` rather
than invoked directly. They are separate so a hook's startup depends on nothing
else the stage links -- `synapse-hook` links no libtree-sitter and needs no C
compiler.

EOF

  printf '## synapse\n\n```\n%s```\n\n' "$(help_for "$SYNAPSE")"

  local sub
  while read -r sub; do
    [ -n "$sub" ] || continue
    printf '### synapse %s\n\n```\n%s```\n\n' "$sub" "$(help_for "$SYNAPSE" "$sub")"
  done < <(subcommands)

  printf '## synapse-hook\n\n```\n%s```\n' "$(help_for "$HOOK")"
}

validate

if [ "$CHECK" = true ]; then
  if [ ! -f "$OUT" ]; then
    echo "generate-cli-reference: $OUT does not exist -- run this script" >&2
    exit 1
  fi
  if diff -q <(render) "$OUT" >/dev/null; then
    echo "docs/cli.md is up to date"
    exit 0
  fi
  echo "generate-cli-reference: docs/cli.md is out of date -- run docs/generate-cli-reference.sh" >&2
  diff <(render) "$OUT" | head -20 >&2
  exit 1
fi

render > "$OUT"
printf 'wrote %s (%s subcommands, %s lines)\n' \
  "$OUT" "$(subcommands | wc -l | tr -d ' ')" "$(wc -l < "$OUT" | tr -d ' ')"
